apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.cronjob }}
  namespace: {{ .Values.namespace }}
spec:
  schedule: {{ .Values.schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: gke-restarter
              image: {{ .Values.image.name }}
              env:
              {{- range $key, $value := .Values.c_env }}
              - name: {{ $key | upper }}
                value: {{ $value | quote }}
              {{- end }}
          restartPolicy: OnFailure
          serviceAccountName: {{ .Values.serviceAccountName }}